server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sandhya246/spring-cloud-config-store.git
          search-paths:
            - '*service'
management:
  endpoints:
    web:
      exposure:
        include: refresh
